# Generated by Django 5.1.9 on 2025-06-04 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='dates',
        ),
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='team',
            name='show_type',
            field=models.CharField(choices=[('Cabaret', 'Cabaret'), ('Drag', 'Drag'), ('Burlesque', 'Burlesque'), ('Queer', 'Queer')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
