# Generated by Django 5.1.9 on 2025-06-10 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_dates_team_city_team_date_team_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='image',
            new_name='main_image',
        ),
        migrations.CreateModel(
            name='TeamImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='teams_gallery/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to='videos/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='teams.team')),
            ],
        ),
    ]
