# Generated by Django 5.1.9 on 2025-07-13 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(blank=True, choices=[('monthly_3', '3€/mois'), ('annual_30', '30€/an'), ('monthly_7', '7€/mois'), ('annual_70', '70€/an'), ('monthly_20', '20€/mois'), ('annual_200', '200€/an')], max_length=20, null=True)),
                ('subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
