# Generated by Django 5.1.9 on 2025-06-04 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='dates',
        ),
        migrations.AddField(
            model_name='show',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='show',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='show',
            name='show_type',
            field=models.CharField(choices=[('Cabaret', 'Cabaret'), ('Drag', 'Drag'), ('Burlesque', 'Burlesque'), ('Queer', 'Queer')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
