# Generated by Django 5.1.9 on 2025-06-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_remove_show_dates_show_city_show_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='featured_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
