# Generated by Django 5.1.9 on 2025-06-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_show_featured_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='booking_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
