# Generated by Django 5.1.9 on 2025-07-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_show_booking_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='image',
            new_name='main_image',
        ),
    ]
